Implement a safe wallet type for storing bitcoins
grigagod/go-wallet pull request #2
Opened 2021-07-07 09:19 UTC by grigagod

2021-07-08 13:46 UTC, xartishuk commented on README.md
> +# Task 2 - Wallet
Write a better readme. Think of this as a real package you're developing, not as a task

2021-07-08 13:46 UTC, xartishuk commented on README.md
> +# Task 2 - Wallet
Rename the repo as well

2021-07-08 13:51 UTC, xartishuk commented on wallet/wallet.go
> +type Bitcoin = float64
Why did you choose to have an alias instead of a new type?
Also, you have a typo in the comment

2021-07-08 13:52 UTC, xartishuk commented on wallet/wallet.go
> +// Deposit encreases wallet balance.
increases

2021-07-08 13:53 UTC, xartishuk commented on wallet/wallet.go
> +func (wal *Wallet) Deposit(val Bitcoin) {
Function receivers are usually named with a single letter. `w` in this case

2021-07-08 13:56 UTC, xartishuk commented on wallet/wallet.go
> +	} else {
You don't need `else` here. "Happy path" should not be indented if possible

2021-07-08 13:59 UTC, xartishuk commented on wallet/wallet.go
> +		return errors.New("Not enough bitcoins in wallet.")
Error messages should not be capitalized, and should not have `.` at the end

2021-07-09 09:19 UTC, grigagod commented on wallet/wallet.go
> +type Bitcoin = float64
To avoid unnecessary type conversions

2021-07-13 12:06 UTC, xartishuk commented on wallet/wallet_test.go
> +	wal.Withdraw(Bitcoin(1))
Imagine if there was a mistake in the `Withdraw()` function, where someone accidentally reversed a check for sufficient funds, which is just writing `>` instead of `<`. Then first withdraw will succeed making `balance=-1`, deposit will succeed making `balance=1`, and second withdraw will return an insufficient funds error. And this test will not fail, since the balance is 1 as expected

2021-07-14 10:06 UTC, xartishuk commented on wallet/wallet.go
> +type Bitcoin float64
update comment

2021-07-14 10:22 UTC, xartishuk commented on wallet/wallet.go
> +}
It would be more convenient to have errors as variables. Your approach would be better in a situation where you want to have differing error messages, but you don't need that here and it makes these errors complex and harder to check.
Try smth like this:
```go
var InsufficientFundsError = errors.New("some message")
var NegativeBitcoinError = errors.New("bitcoin can't be negative")
```

2021-07-14 10:24 UTC, xartishuk commented on wallet/wallet.go
> +}
`Bitcoin.isValid()` would be better

2021-07-14 10:25 UTC, xartishuk commented on wallet/wallet.go
> +	}
don't put blank lines between a call and error check

2021-07-14 10:26 UTC, xartishuk commented on wallet/wallet_test.go
> +	}
you should always check the error first

2021-07-15 09:43 UTC, xartishuk requested changes

2021-07-16 12:32 UTC, xartishuk commented
Your test cases are good, I think we're 99% done. It's considered best practice to structure tests after methods and functions. Refactor your test cases into TestWallet_GetBalance, TestWallet_Deposit, TestWallet_Withdraw. TestWallet_MultipleWorkers is the exception, leave it as is

2021-07-16 12:34 UTC, xartishuk commented on wallet/wallet_test.go
> +		assertError(t, err, NegativeBitcoinError)
For example: move this as a separate case into `TestWallet_Deposit()`

2021-07-16 12:35 UTC, xartishuk commented on wallet/wallet_test.go
> +		assertError(t, err, NegativeBitcoinError)
And this as a separate case into `TestWallet_Withdraw()`

2021-08-02 12:57 UTC, xartishuk approved these changes

2021-11-12 19:51 UTC, merged